In [75]:
def manual_regression(path='data.csv',target='target'):
    # Step 0. Import libraries and read the data
    def read_data(path, target):
        import pandas as pd
        try:
            df = pd.read_csv(path,sep=';')
            return df
        except TypeError:
            print('Data import unsuccessful, please make sure you have your data in csv format.')
        

    # Step 1. Normalisation
    def normalise(df):
        for col in df.columns:
            if(col!=target):
                df[col]=(df[col]-df[col].mean())/df[col].std()
        return df

    # Step 2. Listwise deletion of Null values
    def handle_na(df):
        na_rows = []
        for row in df.index:
            if(len(df.isna().iloc[row].unique())==2):
                na_rows.append(row)
        return df.drop(na_rows)

    df = read_data('data.csv','population')
    df = handle_na(normalise(df))
    return df

In [76]:
manual_regression(path='data.csv',target='population')

        year   college  population
0  -1.587771 -1.049673     5557798
1  -1.449442 -1.156584     5616388
2  -1.311114 -1.584228     5674547
3  -1.172785 -0.942762     5739019
4  -1.034457 -0.728939     5793526
5  -0.896128 -1.049673     5851459
6  -0.757800 -1.263495     5906013
7  -0.619471 -0.515117     5955267
8  -0.481143 -0.515117     5998881
11 -0.066157 -0.194384     6127760
13  0.210500  0.233261     6196638
14  0.348828 -0.194384     6233007
15  0.487157 -0.087473     6278616
16  0.625485  0.660905     6332669
17  0.763814  1.088549     6379599
18  0.902142  0.981638     6424806
19  1.040471  0.447083     6459325
20  1.178799  1.088549     6489965
21  1.317128  1.409283     6516336
22  1.455456  1.516194     6537782
23  1.593785  1.730016     6570902